import type { AgentConfig, ConfigSources, ModelInfo } from '../core/config.js';
import type { AgentPaths } from '../core/paths.js';
import type { EventBus } from '../core/events.js';
import type { AgentLoop } from '../core/loop.js';
import type { ProviderRegistry, ToolRegistry } from '../core/registry.js';
import type { SessionManager } from '../core/session/coordinator.js';
import type { CommandResult, InteractionRequest, PermissionController, SkillSource, ApprovalTool, ToolResult } from '../sdk/index.js';
import type { PluginInspection } from './plugin-inspection.js';
import type { CommandRegistry, SettingsRecord } from './commands.js';
export interface Agent {
  readonly cwd: string;
  readonly paths: AgentPaths;
  readonly configSources: ConfigSources;
  loop: AgentLoop;
  events: EventBus;
  permission: PermissionController;
  session: SessionManager;
  config: AgentConfig;
  tools: { get(name: string): ApprovalTool | undefined; list(): ApprovalTool[]; definitions(): ReturnType<ToolRegistry['definitions']> };
  invokeTool(name: string, input: Record<string, unknown>, signal?: AbortSignal): Promise<ToolResult>;
  providers: ProviderRegistry;
  skillLoader: SkillSource;
  modelInfo(model: string): ModelInfo | undefined;
  knownModels: Array<{ name: string; info?: ModelInfo }>;
  logPath: string;
  plugins: PluginInspection;
  commands: CommandRegistry;
  settings: SettingsRecord[];
  dispatchCommand(line: string, options?: { signal?: AbortSignal; interact?: (request: InteractionRequest) => Promise<string | undefined> }): Promise<CommandResult>;
  dispose(): Promise<void>;
}
